app/models.py
class News:
    '''
    News class to define News Objects
    '''

    def __init__(self,id,name,description,url,category,language, country):
        self.id =id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.language = language
        self.country = country

class Review:

    all_reviews = []

    def __init__(self,news_id,name,description,url,category,language, country):
        self.news_id = news_id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.language = language
        self.country = country


    def save_review(self):
        Review.all_reviews.append(self)


    @classmethod
    def clear_reviews(cls):
        Review.all_reviews.clear()

    @classmethod
    def get_reviews(cls,id):

        response = []

        for review in cls.all_reviews:
            if review.news_id == id:
                response.append(review)

        return response

class news_article:
    '''
    News class to define News Article Objects
    '''

    def __init__(self, source, description,author,title,urlToImage, publishedAt, content, url):
        self.source = source
        self.author = author
        self.description = description
        self.url = url
        self.title = title
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content

class news_article_source:
    def __init__(self, id, name):
        self.id = id
        self.name = name

app/__init__.py
from flask import Flask
from config import config_options
# Initializing app
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    from .request import configure_request
    configure_request(app)
    
    return app


# from app.views import views

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from ..request import get_news, get_source_news
from ..models import Review

# Views
@main.route('/')
def index():
   news_sources = get_news('/sources?')
   return render_template('home_page.html', sources=news_sources)

@main.route('/source/<string:id>')
def get_source(id):
   endpoint = '?sources'+'='+id+'&'
   news_source = get_source_news(endpoint)
   return render_template('news_source.html', source=news_source)

app/views/views.py
from flask import render_template
from app import app
from ..request import get_news
 

# @app.route('/')
# def index():

#     '''
#     View root page function that returns the home page and its data
#     '''
#       # Getting News sources
#     news_sources = get_news('sources')
#     return render_template('home_page.html' , sources = news_sources)

app/templates/home_page.html
{% extends 'index.html' %}

{% block head %}{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-md-10">
      <div class="card">
        <div class="card-body shadow">
          <div class="newsSources d-flex justify-content-center">
            <h3 class="">News Sources</h3>
          </div>
          {% for news_source in sources%}
          <div class="card shadow" style="background-color: rgb(228, 233, 221);">
            <a href="{{url_for('main.get_source',id = news_source.id)}}" class="text-success">
            <div class="card-header" style="background-color: rgb(20, 14, 58);">
              <span class="d-block">
                <h4><small>{{news_source.name}}</small></h4>
              </span>
            </div>
            </a>
            <div class="card-body w-100">
               
                <div class="w-100">
               
                  <p class="media-body pb-3 mb-0 small lh-125">
                    <span class="d-flex justify-content-end text-muted"> 
                    
                      <small>language: {{news_source.language}}</small></span>
                    <strong class="d-block ml-3 text-success">
                    </strong>
                    {{news_source.description}}
                    
                  </p>
                  
                  <p class="mb-2 text-muted align-center"><i>news source category: <span class="text-danger">{{news_source.category}}</span></i></p> 
                  <p class="mb-2 text-muted align-center"><i>news source country: <span class="text-danger">{{news_source.country}}</span></i></p> 
                  <p class="mb-2 text-muted align-center"><i>news source website: <span class="text-danger"><a href="{{news_source.url}}">{{news_source.url}}</a></span></i></p> 

                  

                </div>
               
            </div>
          </div>
          {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" 
     crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" 
     integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" 
     crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

                       
    {% block head %}{% endblock %}
</head>

<body>
    <header class="header-area overlay">
        <nav class="navbar navbar-expand-sm navbar-dark  fixed-top">
            <!-- Toggler/collapsibe Button -->
            <div class="container-fluid">
                <a href="/" class="navbar-brand">
                    <span style="font-family: cursive;">
                        LEPRINT MEDIA
                    </span>
                </a>
                <button class="navbar-toggler ms-auto ms-sm-2" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
                    <span class="menu-icon-bar"></span>
                    <span class="menu-icon-bar"></span>
                    <span class="menu-icon-bar"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-center" id="main-nav">
                    <ul class="navbar-nav ms-2 align-items-end">
                         <li><a href="/" class="nav-item nav-link active"><small>Home</small></a></li>
                        <li><a href="#" class="nav-item nav-link"><small>Science</small></a></li>
                        <li><a href="#" class="nav-item nav-link"><small>Technology</small></a></li>
                        <li><a href="#" class="nav-item nav-link"><small>Sports</small></a></li>
                        <!-- <li class="nav-item">
                            <a class="" href="#">Home</a>
                        </li>
                        <li>
                            <a class="nav-link" href="#">Sports</a>
                        </li>
                        <li>
                            <a class="nav-link" href="#">Technology</a>
                        </li>
                        <li>
                            <a class="nav-link" href="#">Science</a>
                        </li>
                         -->
                    </ul>
                </div>
            </div>
        </nav>
        <div class="overlaybrandContent d-flex justify-content-center w-100" 
        style="position: absolute; margin-top: 15%;">
            <span>
                <h2 class="text-white">
                    <strong>
                        LEPRINT MEDIA
                   </strong> 
                </h2>
                <p style="font-size: 2rem; color: rgb(134, 115, 115);">
                    <i>
                        YOUR NUMBER ONE <br>
                        NEWS SOURCE
                    </i>
                </p>
            </span>
            
           
        </div>
    </header> 
    <div class="newsMainBlock w-100 h-100 clear-top min-vh-100">
    <div class="contentDiv"
    style=" overflow: auto;  padding-bottom:150px;"
    >     
        {% block body %}
   
        {% endblock %}
    </div>

    </div>
    <footer>
        <section id="footer">
            <div class="container">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-sm-5">
                        <ul class="list-unstyled list-inline social text-center">
                            <li><a href="#"><i class="fa fa-twitter"></i></a> @kevin_leresi</li> <br>
                            <li><a href="#"><i class="fa fa-envelope"></i></a> kevinleparwa@gmail.com</li>
                        </ul>
                    </div>
  	
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center text-white">
                        <p>&copy 2021 All right Reversed</p>
                    </div>
                    </hr>
                </div>	
            </div>
        </section>
   
    </footer>
    
</body>
</html>

app/templates/newsS_source_articles.html
{% extends 'index.html' %}


  {% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-4">
            
          </div>
        </div>
      </div>
    </div>
  </div>
  
  {% endblock %}

app/templates/news_source.html
{% extends 'index.html' %}
  {% block body %}
  <div class="container-fluid p-4">
    <div class="container-fluid d-flex justify-content-center bg-primary text-white mb-3">
       <span>
        <h3>
            {{source[1].source.name}}      
          </h3> 
          
       </span>
    </div>
    <div class="row ">
        {% for source_article in source %}
        <div class="col-md-6">
            <div class="card shadow w-100">
                <div class="row p-3 ">
                    <div class="col-md-4 col-sm-12 d-flex justify-content-center m-1">
                        <div class="imgSection">
                            <img class="d-flex" src="{{source_article.urlToImage}}" alt="NEWS IMAGE" width="199px" height="100%">
                        </div>
                    </div>
                    <div class="col-md-7 d-flex justify-content-center">
                        <div class="divContent">
                            <a href="{{source_article.url}}" class="text-danger"><h5>{{source_article.title}}</h5></a>
                            <p><small>{{source_article.description}}</small></p> 
                            <p class="text-muted mt-0 pull-right"><small>{{source_article.author}}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}  
    </div>
  </div>
  {% endblock %}